service: serverless-project

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
          
  goodbye:
    handler: handler.goodbye
    events:
      - http:
          method: get
          path: hello/{name}
  hi:
    handler: handler.hi
    events:
      - http:
          method: post
          path: hi